<?php
class EmotionMobile {
	var $emotion = array(
			0 => '[微笑]',
			1 => '[撇嘴]',
			2 => '[色]',
			3 => '[发呆]',
			4 => '[得意]',
			5 => '[流泪]',
			6 => '[害羞]',
			7 => '[闭嘴]',
			8 => '[睡]',
			9 => '[大哭]',
			10 => '[尴尬]',
			11 => '[发怒]',
			12 => '[调皮]',
			13 => '[呲牙]',
			14 => '[惊讶]',
			15 => '[难过]',
			16 => '[酷]',
			17 => '[冷汗]',
			18 => '[抓狂]',
			19 => '[吐]',
			20 => '[偷笑]',
			21 => '[可爱]',
			22 => '[白眼]',
			23 => '[傲慢]',
			24 => '[饥饿]',
			25 => '[困]',
			26 => '[惊恐]',
			27 => '[流汗]',
			28 => '[憨笑]',
			29 => '[大兵]',
			30 => '[奋斗]',
			31 => '[咒骂]',
			32 => '[疑问]',
			33 => '[嘘..]',
			34 => '[晕]',
			35 => '[折磨]',
			36 => '[衰]',
			37 => '[骷髅]',
			38 => '[敲打]',
			39 => '[再见]',
			40 => '[擦汗]',
			41 => '[抠鼻]',
			42 => '[鼓掌]',
			43 => '[糗大了]',
			44 => '[坏笑]',
			45 => '[左哼哼]',
			46 => '[右哼哼]',
			47 => '[哈欠]',
			48 => '[鄙视]',
			49 => '[委屈]',
			50 => '[快哭了]',
			51 => '[阴险]',
			52 => '[亲亲]',
			53 => '[吓]',
			54 => '[可怜]',
			55 => '[菜刀]',
			56 => '[西瓜]',
			57 => '[啤酒]',
			58 => '[篮球]',
			59 => '[乒乓]',
			60 => '[咖啡]',
			61 => '[饭]',
			62 => '[猪头]',
			63 => '[玫瑰]',
			64 => '[凋谢]',
			65 => '[示爱]',
			66 => '[爱心]',
			67 => '[心碎]',
			68 => '[蛋糕]',
			69 => '[闪电]',
			70 => '[炸弹]',
			71 => '[刀]',
			72 => '[足球]',
			73 => '[瓢虫]',
			74 => '[便便]',
			75 => '[月亮]',
			76 => '[太阳]',
			77 => '[礼物]',
			78 => '[拥抱]',
			79 => '[强]',
			80 => '[弱]',
			81 => '[握手]',
			82 => '[胜利]',
			83 => '[抱拳]',
			84 => '[勾引]',
			85 => '[拳头]',
			86 => '[差劲]',
			87 => '[爱你]',
			88 => '[NO]',
			89 => '[OK]',
			90 => '[爱情]',
			91 => '[飞吻]',
			92 => '[跳跳]',
			93 => '[发抖]',
			94 => '[怄火]',
			95 => '[转圈]',
			96 => '[磕头]',
			97 => '[回头]',
			98 => '[跳绳]',
			99 => '[挥手]',
			100 => '[激动]',
			101 => '[街舞]',
			102 => '[献吻]',
			103 => '[左太极]',
			104 => '[右太极]',
	);
	
	var $emotionreflect = array(
			'[微笑]' => '<img class="expimg" src="/APP/Modules/Community/Tpl/Public/images/smiley/default/e100.gif">',
			'[撇嘴]' => '<img class="expimg" src="/APP/Modules/Community/Tpl/Public/images/smiley/default/e101.gif">',
			'[色]' => '<img class="expimg" src="/APP/Modules/Community/Tpl/Public/images/smiley/default/e102.gif">',
			'[发呆]' => '<img class="expimg" src="/APP/Modules/Community/Tpl/Public/images/smiley/default/e103.gif">',
			'[得意]' => '<img class="expimg" src="/APP/Modules/Community/Tpl/Public/images/smiley/default/e104.gif">',
			'[流泪]' => '<img class="expimg" src="/APP/Modules/Community/Tpl/Public/images/smiley/default/e105.gif">',
			'[害羞]' => '<img class="expimg" src="/APP/Modules/Community/Tpl/Public/images/smiley/default/e106.gif">',
			'[闭嘴]' => '<img class="expimg" src="/APP/Modules/Community/Tpl/Public/images/smiley/default/e107.gif">',
			'[睡]' => '<img class="expimg" src="/APP/Modules/Community/Tpl/Public/images/smiley/default/e108.gif">',
			'[大哭]' => '<img class="expimg" src="/APP/Modules/Community/Tpl/Public/images/smiley/default/e109.gif">',
			'[尴尬]' => '<img class="expimg" src="/APP/Modules/Community/Tpl/Public/images/smiley/default/e110.gif">',
			'[发怒]' => '<img class="expimg" src="/APP/Modules/Community/Tpl/Public/images/smiley/default/e111.gif">',
			'[调皮]' => '<img class="expimg" src="/APP/Modules/Community/Tpl/Public/images/smiley/default/e112.gif">',
			'[呲牙]' => '<img class="expimg" src="/APP/Modules/Community/Tpl/Public/images/smiley/default/e113.gif">',
			'[惊讶]' => '<img class="expimg" src="/APP/Modules/Community/Tpl/Public/images/smiley/default/e114.gif">',
			'[难过]' => '<img class="expimg" src="/APP/Modules/Community/Tpl/Public/images/smiley/default/e115.gif">',
			'[酷]' => '<img class="expimg" src="/APP/Modules/Community/Tpl/Public/images/smiley/default/e116.gif">',
			'[冷汗]' => '<img class="expimg" src="/APP/Modules/Community/Tpl/Public/images/smiley/default/e117.gif">',
			'[抓狂]' => '<img class="expimg" src="/APP/Modules/Community/Tpl/Public/images/smiley/default/e118.gif">',
			'[吐]' => '<img class="expimg" src="/APP/Modules/Community/Tpl/Public/images/smiley/default/e119.gif">',
			'[偷笑]' => '<img class="expimg" src="/APP/Modules/Community/Tpl/Public/images/smiley/default/e120.gif">',
			'[可爱]' => '<img class="expimg" src="/APP/Modules/Community/Tpl/Public/images/smiley/default/e121.gif">',
			'[白眼]' => '<img class="expimg" src="/APP/Modules/Community/Tpl/Public/images/smiley/default/e122.gif">',
			'[傲慢]' => '<img class="expimg" src="/APP/Modules/Community/Tpl/Public/images/smiley/default/e123.gif">',
			'[饥饿]' => '<img class="expimg" src="/APP/Modules/Community/Tpl/Public/images/smiley/default/e124.gif">',
			'[困]' => '<img class="expimg" src="/APP/Modules/Community/Tpl/Public/images/smiley/default/e125.gif">',
			'[惊恐]' => '<img class="expimg" src="/APP/Modules/Community/Tpl/Public/images/smiley/default/e126.gif">',
			'[流汗]' => '<img class="expimg" src="/APP/Modules/Community/Tpl/Public/images/smiley/default/e127.gif">',
			'[憨笑]' => '<img class="expimg" src="/APP/Modules/Community/Tpl/Public/images/smiley/default/e128.gif">',
			'[大兵]' => '<img class="expimg" src="/APP/Modules/Community/Tpl/Public/images/smiley/default/e129.gif">',
			'[奋斗]' => '<img class="expimg" src="/APP/Modules/Community/Tpl/Public/images/smiley/default/e130.gif">',
			'[咒骂]' => '<img class="expimg" src="/APP/Modules/Community/Tpl/Public/images/smiley/default/e131.gif">',
			'[疑问]' => '<img class="expimg" src="/APP/Modules/Community/Tpl/Public/images/smiley/default/e132.gif">',
			'[嘘..]' => '<img class="expimg" src="/APP/Modules/Community/Tpl/Public/images/smiley/default/e133.gif">',
			'[晕]' => '<img class="expimg" src="/APP/Modules/Community/Tpl/Public/images/smiley/default/e134.gif">',
			'[折磨]' => '<img class="expimg" src="/APP/Modules/Community/Tpl/Public/images/smiley/default/e135.gif">',
			'[衰]' => '<img class="expimg" src="/APP/Modules/Community/Tpl/Public/images/smiley/default/e136.gif">',
			'[骷髅]' => '<img class="expimg" src="/APP/Modules/Community/Tpl/Public/images/smiley/default/e137.gif">',
			'[敲打]' => '<img class="expimg" src="/APP/Modules/Community/Tpl/Public/images/smiley/default/e138.gif">',
			'[再见]' => '<img class="expimg" src="/APP/Modules/Community/Tpl/Public/images/smiley/default/e139.gif">',
			'[擦汗]' => '<img class="expimg" src="/APP/Modules/Community/Tpl/Public/images/smiley/default/e140.gif">',
			'[抠鼻]' => '<img class="expimg" src="/APP/Modules/Community/Tpl/Public/images/smiley/default/e141.gif">',
			'[鼓掌]' => '<img class="expimg" src="/APP/Modules/Community/Tpl/Public/images/smiley/default/e142.gif">',
			'[糗大了]' => '<img class="expimg" src="/APP/Modules/Community/Tpl/Public/images/smiley/default/e143.gif">',
			'[坏笑]' => '<img class="expimg" src="/APP/Modules/Community/Tpl/Public/images/smiley/default/e144.gif">',
			'[左哼哼]' => '<img class="expimg" src="/APP/Modules/Community/Tpl/Public/images/smiley/default/e145.gif">',
			'[右哼哼]' => '<img class="expimg" src="/APP/Modules/Community/Tpl/Public/images/smiley/default/e146.gif">',
			'[哈欠]' => '<img class="expimg" src="/APP/Modules/Community/Tpl/Public/images/smiley/default/e147.gif">',
			'[鄙视]' => '<img class="expimg" src="/APP/Modules/Community/Tpl/Public/images/smiley/default/e148.gif">',
			'[委屈]' => '<img class="expimg" src="/APP/Modules/Community/Tpl/Public/images/smiley/default/e149.gif">',
			'[快哭了]' => '<img class="expimg" src="/APP/Modules/Community/Tpl/Public/images/smiley/default/e150.gif">',
			'[阴险]' => '<img class="expimg" src="/APP/Modules/Community/Tpl/Public/images/smiley/default/e151.gif">',
			'[亲亲]' => '<img class="expimg" src="/APP/Modules/Community/Tpl/Public/images/smiley/default/e152.gif">',
			'[吓]' => '<img class="expimg" src="/APP/Modules/Community/Tpl/Public/images/smiley/default/e153.gif">',
			'[可怜]' => '<img class="expimg" src="/APP/Modules/Community/Tpl/Public/images/smiley/default/e154.gif">',
			'[菜刀]' => '<img class="expimg" src="/APP/Modules/Community/Tpl/Public/images/smiley/default/e155.gif">',
			'[西瓜]' => '<img class="expimg" src="/APP/Modules/Community/Tpl/Public/images/smiley/default/e156.gif">',
			'[啤酒]' => '<img class="expimg" src="/APP/Modules/Community/Tpl/Public/images/smiley/default/e157.gif">',
			'[篮球]' => '<img class="expimg" src="/APP/Modules/Community/Tpl/Public/images/smiley/default/e158.gif">',
			'[乒乓]' => '<img class="expimg" src="/APP/Modules/Community/Tpl/Public/images/smiley/default/e159.gif">',
			'[咖啡]' => '<img class="expimg" src="/APP/Modules/Community/Tpl/Public/images/smiley/default/e160.gif">',
			'[饭]' => '<img class="expimg" src="/APP/Modules/Community/Tpl/Public/images/smiley/default/e161.gif">',
			'[猪头]' => '<img class="expimg" src="/APP/Modules/Community/Tpl/Public/images/smiley/default/e162.gif">',
			'[玫瑰]' => '<img class="expimg" src="/APP/Modules/Community/Tpl/Public/images/smiley/default/e163.gif">',
			'[凋谢]' => '<img class="expimg" src="/APP/Modules/Community/Tpl/Public/images/smiley/default/e164.gif">',
			'[示爱]' => '<img class="expimg" src="/APP/Modules/Community/Tpl/Public/images/smiley/default/e165.gif">',
			'[爱心]' => '<img class="expimg" src="/APP/Modules/Community/Tpl/Public/images/smiley/default/e166.gif">',
			'[心碎]' => '<img class="expimg" src="/APP/Modules/Community/Tpl/Public/images/smiley/default/e167.gif">',
			'[蛋糕]' => '<img class="expimg" src="/APP/Modules/Community/Tpl/Public/images/smiley/default/e168.gif">',
			'[闪电]' => '<img class="expimg" src="/APP/Modules/Community/Tpl/Public/images/smiley/default/e169.gif">',
			'[炸弹]' => '<img class="expimg" src="/APP/Modules/Community/Tpl/Public/images/smiley/default/e170.gif">',
			'[刀]' => '<img class="expimg" src="/APP/Modules/Community/Tpl/Public/images/smiley/default/e171.gif">',
			'[足球]' => '<img class="expimg" src="/APP/Modules/Community/Tpl/Public/images/smiley/default/e172.gif">',
			'[瓢虫]' => '<img class="expimg" src="/APP/Modules/Community/Tpl/Public/images/smiley/default/e173.gif">',
			'[便便]' => '<img class="expimg" src="/APP/Modules/Community/Tpl/Public/images/smiley/default/e174.gif">',
			'[月亮]' => '<img class="expimg" src="/APP/Modules/Community/Tpl/Public/images/smiley/default/e175.gif">',
			'[太阳]' => '<img class="expimg" src="/APP/Modules/Community/Tpl/Public/images/smiley/default/e176.gif">',
			'[礼物]' => '<img class="expimg" src="/APP/Modules/Community/Tpl/Public/images/smiley/default/e177.gif">',
			'[拥抱]' => '<img class="expimg" src="/APP/Modules/Community/Tpl/Public/images/smiley/default/e178.gif">',
			'[强]' => '<img class="expimg" src="/APP/Modules/Community/Tpl/Public/images/smiley/default/e179.gif">',
			'[弱]' => '<img class="expimg" src="/APP/Modules/Community/Tpl/Public/images/smiley/default/e180.gif">',
			'[握手]' => '<img class="expimg" src="/APP/Modules/Community/Tpl/Public/images/smiley/default/e181.gif">',
			'[胜利]' => '<img class="expimg" src="/APP/Modules/Community/Tpl/Public/images/smiley/default/e182.gif">',
			'[抱拳]' => '<img class="expimg" src="/APP/Modules/Community/Tpl/Public/images/smiley/default/e183.gif">',
			'[勾引]' => '<img class="expimg" src="/APP/Modules/Community/Tpl/Public/images/smiley/default/e184.gif">',
			'[拳头]' => '<img class="expimg" src="/APP/Modules/Community/Tpl/Public/images/smiley/default/e185.gif">',
			'[差劲]' => '<img class="expimg" src="/APP/Modules/Community/Tpl/Public/images/smiley/default/e186.gif">',
			'[爱你]' => '<img class="expimg" src="/APP/Modules/Community/Tpl/Public/images/smiley/default/e187.gif">',
			'[NO]' => '<img class="expimg" src="/APP/Modules/Community/Tpl/Public/images/smiley/default/e188.gif">',
			'[OK]' => '<img class="expimg" src="/APP/Modules/Community/Tpl/Public/images/smiley/default/e189.gif">',
			'[爱情]' => '<img class="expimg" src="/APP/Modules/Community/Tpl/Public/images/smiley/default/e190.gif">',
			'[飞吻]' => '<img class="expimg" src="/APP/Modules/Community/Tpl/Public/images/smiley/default/e191.gif">',
			'[跳跳]' => '<img class="expimg" src="/APP/Modules/Community/Tpl/Public/images/smiley/default/e192.gif">',
			'[发抖]' => '<img class="expimg" src="/APP/Modules/Community/Tpl/Public/images/smiley/default/e193.gif">',
			'[怄火]' => '<img class="expimg" src="/APP/Modules/Community/Tpl/Public/images/smiley/default/e194.gif">',
			'[转圈]' => '<img class="expimg" src="/APP/Modules/Community/Tpl/Public/images/smiley/default/e195.gif">',
			'[磕头]' => '<img class="expimg" src="/APP/Modules/Community/Tpl/Public/images/smiley/default/e196.gif">',
			'[回头]' => '<img class="expimg" src="/APP/Modules/Community/Tpl/Public/images/smiley/default/e197.gif">',
			'[跳绳]' => '<img class="expimg" src="/APP/Modules/Community/Tpl/Public/images/smiley/default/e198.gif">',
			'[挥手]' => '<img class="expimg" src="/APP/Modules/Community/Tpl/Public/images/smiley/default/e199.gif">',
			'[激动]' => '<img class="expimg" src="/APP/Modules/Community/Tpl/Public/images/smiley/default/e200.gif">',
			'[街舞]' => '<img class="expimg" src="/APP/Modules/Community/Tpl/Public/images/smiley/default/e201.gif">',
			'[献吻]' => '<img class="expimg" src="/APP/Modules/Community/Tpl/Public/images/smiley/default/e202.gif">',
			'[左太极]' => '<img class="expimg" src="/APP/Modules/Community/Tpl/Public/images/smiley/default/e203.gif">',
			'[右太极]' => '<img class="expimg" src="/APP/Modules/Community/Tpl/Public/images/smiley/default/e204.gif">',
	);
	
	public function replaceEmotion($origin = '') {
		$prefix = 'bianbianloveqianqian'; // 防止一个表情出现在0位置
		$check = $prefix . $origin;
		
		for($i = 0; $i < count($this->emotion); $i ++){
			$pos = strpos($check, $this->emotion[$i]);
			if($pos){
				$check = str_replace($this->emotion[$i], $this->emotionreflect [ $this->emotion [$i] ], $check);
			}
		}
		$final = str_replace($prefix, '', $check);
		return $final;
	}
}
?>